### ISSUE TITLE
Collaboration on this project

### ISSUE THREAD

**Issue by mlange-42** [francisco-perez-sorrosal/mdbook-bib#1]
Hi @francisco-perez-sorrosal,

while thinking about a bibtex reference preprocessor for mdBook as a next hobby project, I stumbled upon your brand new repository. Instead of starting a competing project, I would like to ask whether you welcome contributions?

A few ideas for features/possible contributions:

* Render only the cited items in the bibliography. I.e. when using your all-in-one bib file with a four-digit number of entries, only show what was actually used in the text. I would probably start with a PR on that.
* An option for per-chapter bibliographies, e.g. for edited books with multiple authors/essays
* Bibliography and in-line citation styles (~~syntax like/close to/subset of LaTeX~~ EDIT: or through a custom `.hbs` file)
  * Incl. sorting of the bibliography, e.g. by first author or by citation order

I have only a few months of (however, fairly intensive) Rust experience. You may want to assess by a look into my Rust repositories.

Thanks for starting this very useful project!
Regards!

**Comment by francisco-perez-sorrosal** [comment]
Hey Martin (@mlange-42) !

Thanks for appreciating the project! And of course, you are more than welcome aboard if you want! 

I started this as a PR into the mdbook project itself a few months ago (https://github.com/rust-lang/mdBook/pull/1351) but Eric Huss (one of the mdbook contributors) suggested me to do it as a plugin. I had literally Zero experience with Rust at that time, and it took me just one week to implement it. So don't worry about your Rust experience;  I probably have less than you :-) However, since I didn't have much time back then I paused the plugin effort basically till a couple of weeks ago (and here we are.) 

Regarding your contributions you can work on what you feel like. I thought the same about the one on render only items cited in the book, and that's low hanging fruit, so maybe you can start with that! Maybe a parameter to decide the level of render would be nice to have (e.g. render-bib=[all,cited] or something like that) You can create a separate issue for each feature you want to work and we can discuss it there :-)

A couple of days ago I started working on few cosmetics (e.g. add js code in to copy the citation key from the bibliography into the clipboard) and adding more tests, and I plan to continue as soon as I have some time.

Thanks again!

**Comment by mlange-42** [comment]
Thank for your reply, great to hear/read!

> I started this as a PR into the mdbook project itself a few months ago

I have seen that, and I think a plugin is indeed the preferable solution.

> I had literally Zero experience with Rust at that time, and it took me just one week to implement it.

Wow, that's tough. 😎 

> render only items cited in the book, and that's low hanging fruit

Yes, therefore... It is probably a good start get to know the code.

> You can create a separate issue for each feature you want to work and we can discuss it there :-)

I will. Just didn't want to spam you without your agreement. So see you there...
