### ISSUE TITLE
Citations from sub-directory link to wrong bibliography.html

### ISSUE THREAD

**Issue by mlange-42** [francisco-perez-sorrosal/mdbook-bib#24]
When citing in a file that is in a sub-directory of the book sources, the same sub-directory is assumed for the linked `bibliography.html` file, while the file is actually not in that directory.

Example project struture:

```plaintext
root
  |-- src
  |     |-- chapter-1
  |     |     `-- section-1-1.md
  |     |-- bibliography.bib
  |     `-- SUMMARY.md
  `-- book.toml
```

When citing in `section-1-1.md`, citations link to `chapter-1/bibliography.bib`, but should link to `bibliography.bib` only.

**Comment by francisco-perez-sorrosal** [comment]
Hey Martin,

I'have this directory structure in my books:

```
root
  |-- src
  |     |-- chapter-1
  |     |     `-- section-1-1.md
  |     `-- SUMMARY.md
  `-- bibliography.bib
  `-- book.toml
```
and this `book.toml` content:
```
[book}
...
[preprocessor.bib]
bibliography = "bibliography.bib"
```
and it works for me when I have a cite in `section-1-1.md`.

I've tried also:
```
root
  |-- src
  |     |-- chapter-1
  |     |     `-- section-1-1.md
  |     |-- bibliography.bib
  |     `-- SUMMARY.md
  `-- book.toml
```
with this `book.toml` content:
```
[book}
...
[preprocessor.bib]
bibliography = "src/bibliography.bib"
```
and it works well too.

I put the bibliography file at the level of the `book.toml` because it seemed ok to me at that time, as it was referenced in that same file. 

So I guess there are two solutions; 1) Clarify in the documentation the possible directory structures as I did above, or -as I guess you are assuming- 2) consider the bibliography config attribute as purely a filename, and treat and put the bibliography file as a content that belongs to the sources of a book. In this case also I would add the dir structure to the documentation just in case. Also if we go for the solution 2) we need to consider also that when the bibliography is downloaded from Zotero, it should be saved also under `/src`.
